First we have to import the neccessary Libraries, though we won't be using Torch very much, as I am more comfortable with Numpy

In [180]:
import numpy as np
import torch as tc
import pandas as pd

We will now do the simple process of importing the Dataset using Pandas

In [181]:
URL = 'https://bit.ly/palmerpenguinscsv'
data = pd.read_csv(URL)
data.head()

rowid species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0      1  Adelie  Torgersen            39.1           18.7              181.0   
1      2  Adelie  Torgersen            39.5           17.4              186.0   
2      3  Adelie  Torgersen            40.3           18.0              195.0   
3      4  Adelie  Torgersen             NaN            NaN                NaN   
4      5  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
3          NaN     NaN  2007  
4       3450.0  female  2007

We must delete all Missing Data from dataframe. We will also filter out rows with output species of Adelie to make a simple Binary Classifier

In [182]:
data.dropna(inplace = True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 333 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   rowid              333 non-null    int64  
 1   species            333 non-null    object 
 2   island             333 non-null    object 
 3   bill_length_mm     333 non-null    float64
 4   bill_depth_mm      333 non-null    float64
 5   flipper_length_mm  333 non-null    float64
 6   body_mass_g        333 non-null    float64
 7   sex                333 non-null    object 
 8   year               333 non-null    int64  
dtypes: float64(4), int64(2), object(3)
memory usage: 26.0+ KB


In [183]:
data = data[data['species'] != 'Adelie']

We will now create a numpy array of the filtered dataframe, and transpose it to make things simple

In [193]:
data_nump = np.array([data['bill_length_mm'], data['bill_depth_mm'], data['flipper_length_mm'], data['body_mass_g'],data['species']])
data_nump = np.transpose(data_nump)
data_nump


array([[46.1, 13.2, 211.0, 4500.0, 'Gentoo'],
       [50.0, 16.3, 230.0, 5700.0, 'Gentoo'],
       [48.7, 14.1, 210.0, 4450.0, 'Gentoo'],
       [50.0, 15.2, 218.0, 5700.0, 'Gentoo'],
       [47.6, 14.5, 215.0, 5400.0, 'Gentoo'],
       [46.5, 13.5, 210.0, 4550.0, 'Gentoo'],
       [45.4, 14.6, 211.0, 4800.0, 'Gentoo'],
       [46.7, 15.3, 219.0, 5200.0, 'Gentoo'],
       [43.3, 13.4, 209.0, 4400.0, 'Gentoo'],
       [46.8, 15.4, 215.0, 5150.0, 'Gentoo'],
       [40.9, 13.7, 214.0, 4650.0, 'Gentoo'],
       [49.0, 16.1, 216.0, 5550.0, 'Gentoo'],
       [45.5, 13.7, 214.0, 4650.0, 'Gentoo'],
       [48.4, 14.6, 213.0, 5850.0, 'Gentoo'],
       [45.8, 14.6, 210.0, 4200.0, 'Gentoo'],
       [49.3, 15.7, 217.0, 5850.0, 'Gentoo'],
       [42.0, 13.5, 210.0, 4150.0, 'Gentoo'],
       [49.2, 15.2, 221.0, 6300.0, 'Gentoo'],
       [46.2, 14.5, 209.0, 4800.0, 'Gentoo'],
       [48.7, 15.1, 222.0, 5350.0, 'Gentoo'],
       [50.2, 14.3, 218.0, 5700.0, 'Gentoo'],
       [45.1, 14.5, 215.0, 5000.0,

Instead of using PyTorch's rand permutation, we will be using numpy's Shuffle Function

In [194]:
np.random.shuffle(data_nump)

In [195]:
print(data_nump)

[[51.5 18.7 187.0 3250.0 'Chinstrap']
 [48.4 14.4 203.0 4625.0 'Gentoo']
 [42.8 14.2 209.0 4700.0 'Gentoo']
 [51.1 16.3 220.0 6000.0 'Gentoo']
 [45.5 17.0 196.0 3500.0 'Chinstrap']
 [42.6 13.7 213.0 4950.0 'Gentoo']
 [46.4 17.8 191.0 3700.0 'Chinstrap']
 [50.7 19.7 203.0 4050.0 'Chinstrap']
 [54.3 15.7 231.0 5650.0 'Gentoo']
 [40.9 16.6 187.0 3200.0 'Chinstrap']
 [47.0 17.3 185.0 3700.0 'Chinstrap']
 [45.5 13.7 214.0 4650.0 'Gentoo']
 [45.3 13.7 210.0 4300.0 'Gentoo']
 [50.4 15.3 224.0 5550.0 'Gentoo']
 [44.0 13.6 208.0 4350.0 'Gentoo']
 [49.2 15.2 221.0 6300.0 'Gentoo']
 [46.5 14.8 217.0 5200.0 'Gentoo']
 [46.6 14.2 210.0 4850.0 'Gentoo']
 [48.7 15.7 208.0 5350.0 'Gentoo']
 [47.6 18.3 195.0 3850.0 'Chinstrap']
 [49.2 18.2 195.0 4400.0 'Chinstrap']
 [47.8 15.0 215.0 5650.0 'Gentoo']
 [45.7 17.3 193.0 3600.0 'Chinstrap']
 [47.2 13.7 214.0 4925.0 'Gentoo']
 [45.2 13.8 215.0 4750.0 'Gentoo']
 [46.8 16.1 215.0 5500.0 'Gentoo']
 [50.5 15.9 225.0 5400.0 'Gentoo']
 [44.4 17.3 219.0 5250.0 'Ge

Now we will separate the inputs from the outputs

In [206]:
data_inputs = data_nump[:,:4]
data_outputs = data_nump[:,4]



We will also convert our outputs to numerical format (-1 for Gentoo and 1 for Chinstrap)

In [207]:
for d in range (data_outputs.size):
  if (data_outputs[d] == 'Gentoo'):
    data_outputs[d] = -1
  elif(data_outputs[d] == 'Chinstrap'):
    data_outputs[d] = 1

In [208]:
data_outputs




array([1, -1, -1, -1, 1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1,
       -1, 1, 1, -1, 1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1,
       1, -1, -1, -1, -1, -1, 1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, -1,
       1, 1, -1, 1, -1, -1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, 1, -1, -1,
       1, -1, 1, 1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1,
       -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, 1, 1, -1, -1, 1, -1, -1,
       1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, 1,
       1, -1, 1, -1, 1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1,
       -1, 1, -1, 1, -1, 1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1, -1, -1,
       -1, -1, 1, -1, 1, -1, -1, 1, -1, 1, 1, -1, -1, -1, 1, -1, -1, 1,
       -1, -1, 1, -1], dtype=object)

Now we will split our dataset into Training and Validation Sets

In [222]:
validation = int(np.floor(0.2*data_outputs.size))
training = data_outputs.size - validation
train_X = data_inputs[:training, :]
train_Y = data_outputs[:training]
Valid_X = data_inputs[training:, :]
Valid_Y = data_outputs[training:]



Now we will Standardize our Inputs, so the ranges are much more consistent, by using mean and standard deviation

In [224]:
train_mean = np.mean(train_X, axis = 0)
train_std = np.std(train_X, axis =0,  dtype = 'float32')

train_X = (train_X-train_mean)/train_std
valid_X = (Valid_X-train_mean)/train_std

In [229]:
X_row , X_column = train_X.shape

Now we create a random set of Weights which will be augmented with a bias. This makes the weights a 5x1 instead of 4x1

In [231]:
np.random.seed(42)
Weights = np.random.rand((X_column)+1)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

Now we will define the activation function

In [233]:
def activation(z):
  return ((z>=0)*2.0 - 1.0)


We will also augment our Training Inputs by adding a column of 1s to account for the bias

In [234]:
train_X = np.column_stack((train_X, np.ones(X_row)))


In [237]:
Weights.shape

(5,)

We will now create a Simple Perceptron model that is able to Feedforward using the inputs and weights

In [238]:
def perceptron(X,W):
  z = np.dot(X,W)
  return (activation(z))

In [242]:
predicted_outputs = perceptron(train_X, Weights)

In order to backprop, we must update the weights by adding a weight update term that must be calculated using the risduals multiplied by their respective inputs

In [257]:
def weight_update(predicted, actual, inputs):
  return np.dot((0.01)*(actual- predicted), inputs)

In [265]:
w= weight_update(predicted_outputs,train_Y, train_X)

Now we will calculate the Accuracy by just taking the mean of the difference between the Actual values vs the Predicted values of the Training dataset

In [263]:
def acc(predicted, actual):
 return ((actual - predicted)).mean()

We seem to get an accuracy of 40% which isn't great but this is the output that used randomized weights and biases, without any updates

In [264]:
acc(predicted_outputs, train_Y)

-0.4

We will now iterate the same process using the Validation Set as well as using the updated weights values

In [266]:
Weights_new = Weights + w

In [268]:
XV_row , XV_column =Valid_X.shape

In [269]:
Valid_X = np.column_stack((Valid_X, np.ones(XV_row)))

In [270]:
predicted_outputs_v = perceptron(Valid_X, Weights_new)

In [272]:
w_v = weight_update(predicted_outputs_v,Valid_Y,Valid_X)

array([16.288, 6.226000000000001, 66.46, 1303.5, 0.34], dtype=object)

We do now notice that the accuracy has improved by alot. However upon closer inspection, this doesn't really mean that model is doing good, as we notice that the model seems to constantly be predicting values of -1. This can maybe be improved by running the data for more epochs, but we at least demonstrated that the Perceptron model code works

In [273]:
acc(predicted_outputs_v, Valid_Y)

0.918918918918919

In [274]:
predicted_outputs_v

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [275]:
Valid_Y

array([-1, 1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1, -1, -1, -1, -1, 1, -1,
       1, -1, -1, 1, -1, 1, 1, -1, -1, -1, 1, -1, -1, 1, -1, -1, 1, -1],
      dtype=object)